mysql:
  ip: "gocloudcoder.com"
  port: "3306"
  username: "qn-server"
  database: "qn-server"
  password: "000000"

qiniu:
  ak: "zM_pCg7E1kBvwD0DlGQUadtxVGkumuKNQIDVI4Nl"
  sk: "P2mdTgHaJ7PPX7cggzpBHti-VKppSh-Mqkj-hWeO"
  bucket: "nj-jay"